// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CustomizeAnimation {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSSlider __mt_slider;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("setWidth:")]
		partial void setWidth (MonoMac.AppKit.NSSlider sender);

		[MonoMac.Foundation.Connect("slider")]
		private global::MonoMac.AppKit.NSSlider slider {
			get {
				this.__mt_slider = ((global::MonoMac.AppKit.NSSlider)(this.GetNativeField("slider")));
				return this.__mt_slider;
			}
			set {
				this.__mt_slider = value;
				this.SetNativeField("slider", value);
			}
		}
	}
	
	// Should subclass MonoMac.AppKit.NSView
	[MonoMac.Foundation.Register("MyView")]
	public partial class MyView {
		
		private global::MonoMac.AppKit.NSSlider __mt_slider;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("setWidth:")]
		partial void setWidth (MonoMac.AppKit.NSSlider sender);

		[MonoMac.Foundation.Connect("slider")]
		private global::MonoMac.AppKit.NSSlider slider {
			get {
				this.__mt_slider = ((global::MonoMac.AppKit.NSSlider)(this.GetNativeField("slider")));
				return this.__mt_slider;
			}
			set {
				this.__mt_slider = value;
				this.SetNativeField("slider", value);
			}
		}
	}
}
