#!/usr/bin/env python

import os
import sys
import xml.dom.minidom as DOM

def migrate_guid (project):
	for node in project.getElementsByTagName ('ProjectTypeGuids'):
		old = node.firstChild.nodeValue
		node.firstChild.nodeValue = old.replace (
			'{948B3504-5B70-4649-8FE4-BDE1FB46EC69}',
			'{42C0BBD9-55CE-4FC1-8D90-A7348ABAFB23}')
		return node.firstChild.nodeValue != old

def migrate_reference (project):
	xammac_added = False
	for ref in project.getElementsByTagName ('Reference'):
		include = ref.attributes['Include']
		if include:
			name = include.value.lower ()
			if name == 'monomac' or name.startswith ('monomac '):
				if not xammac_added:
					ref.attributes['Include'] = 'XamMac'
					while ref.firstChild:
						ref.removeChild (ref.firstChild)
					xammac_added = True
	return xammac_added

def migrate_project (path):
	with open (path, 'r') as fp:
		eof_newline = fp.read ().endswith ('\n')
	
	project = DOM.parse (path)

	a = migrate_guid (project)
	b = migrate_reference (project)

	if not a and not b:
		return

	xml = project.toxml ('utf-8')
	xml = xml.replace ('"utf-8"?>', '"utf-8"?>\n')
	xml = xml.replace ('/>', ' />')

	with open (path, 'w') as fp:
		fp.write (xml)
		if eof_newline:
			fp.write ('\n')

migrate_project (sys.argv[1])
