// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using AppKit;

namespace PredicateEditorSample {
	
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("MyWindow")]
	public partial class MyWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("MyWindowController")]
	public partial class MyWindowController {
		
		private global::AppKit.NSArrayController __mt_mySearchResults;
		
		private global::AppKit.NSTableView __mt_myTableView;
		
		private NSPredicateEditor __mt_predicateEditor;
		
		private global::AppKit.NSProgressIndicator __mt_progressSearch;
		
		private global::AppKit.NSTextField __mt_progressSearchLabel;
		
		private global::AppKit.NSView __mt_progressView;
		
		#pragma warning disable 0169
		[Foundation.Export("predicateEditorChanged:")]
		partial void predicateEditorChanged (Foundation.NSObject sender);

		[Foundation.Connect("mySearchResults")]
		private global::AppKit.NSArrayController mySearchResults {
			get {
				this.__mt_mySearchResults = ((global::AppKit.NSArrayController)(this.GetNativeField("mySearchResults")));
				return this.__mt_mySearchResults;
			}
			set {
				this.__mt_mySearchResults = value;
				this.SetNativeField("mySearchResults", value);
			}
		}
		
		[Foundation.Connect("myTableView")]
		private global::AppKit.NSTableView myTableView {
			get {
				this.__mt_myTableView = ((global::AppKit.NSTableView)(this.GetNativeField("myTableView")));
				return this.__mt_myTableView;
			}
			set {
				this.__mt_myTableView = value;
				this.SetNativeField("myTableView", value);
			}
		}
		
		[Foundation.Connect("predicateEditor")]
		private NSPredicateEditor predicateEditor {
			get {
				this.__mt_predicateEditor = ((NSPredicateEditor)(this.GetNativeField("predicateEditor")));
				return this.__mt_predicateEditor;
			}
			set {
				this.__mt_predicateEditor = value;
				this.SetNativeField("predicateEditor", value);
			}
		}
		
		[Foundation.Connect("progressSearch")]
		private global::AppKit.NSProgressIndicator progressSearch {
			get {
				this.__mt_progressSearch = ((global::AppKit.NSProgressIndicator)(this.GetNativeField("progressSearch")));
				return this.__mt_progressSearch;
			}
			set {
				this.__mt_progressSearch = value;
				this.SetNativeField("progressSearch", value);
			}
		}
		
		[Foundation.Connect("progressSearchLabel")]
		private global::AppKit.NSTextField progressSearchLabel {
			get {
				this.__mt_progressSearchLabel = ((global::AppKit.NSTextField)(this.GetNativeField("progressSearchLabel")));
				return this.__mt_progressSearchLabel;
			}
			set {
				this.__mt_progressSearchLabel = value;
				this.SetNativeField("progressSearchLabel", value);
			}
		}
		
		[Foundation.Connect("progressView")]
		private global::AppKit.NSView progressView {
			get {
				this.__mt_progressView = ((global::AppKit.NSView)(this.GetNativeField("progressView")));
				return this.__mt_progressView;
			}
			set {
				this.__mt_progressView = value;
				this.SetNativeField("progressView", value);
			}
		}
	}
}
