// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Rulers {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[Foundation.Register("MyWindow")]
	public partial class MyWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[Foundation.Register("MyWindowController")]
	public partial class MyWindowController {
		
		private RectsView __mt_rectsView;
		
		#pragma warning disable 0169
		[Foundation.Connect("rectsView")]
		private RectsView rectsView {
			get {
				this.__mt_rectsView = ((RectsView)(this.GetNativeField("rectsView")));
				return this.__mt_rectsView;
			}
			set {
				this.__mt_rectsView = value;
				this.SetNativeField("rectsView", value);
			}
		}
	}
	
	// Should subclass MonoMac.AppKit.NSView
	[Foundation.Register("RectsView")]
	public partial class RectsView {
		
		#pragma warning disable 0169
		[Foundation.Export("lockSelectedItem:")]
		partial void lockSelectedItem (Foundation.NSObject sender);

		[Foundation.Export("nestle:")]
		partial void nestle (Foundation.NSObject sender);

		[Foundation.Export("zoomIn:")]
		partial void zoomIn (Foundation.NSObject sender);

		[Foundation.Export("zoomOut:")]
		partial void zoomOut (Foundation.NSObject sender);
}
}
