// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DrawerMadness {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[Foundation.Register("ParentWindow")]
	public partial class ParentWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[Foundation.Register("ParentWindowController")]
	public partial class ParentWindowController {
		
		private global::AppKit.NSDrawer __mt_leftDrawer;
		
		private global::AppKit.NSButton __mt_lowerRightAllowClose;
		
		private global::AppKit.NSWindow __mt_myParentWindow;
		
		private global::AppKit.NSButton __mt_upperRightAllowClose;
		
		#pragma warning disable 0169
		[Foundation.Export("closeBottomDrawer:")]
		partial void closeBottomDrawer (Foundation.NSObject sender);

		[Foundation.Export("closeLeftDrawer:")]
		partial void closeLeftDrawer (Foundation.NSObject sender);

		[Foundation.Export("closeLowerRightDrawer:")]
		partial void closeLowerRightDrawer (Foundation.NSObject sender);

		[Foundation.Export("closeUpperRightDrawer:")]
		partial void closeUpperRightDrawer (Foundation.NSObject sender);

		[Foundation.Export("openBottomDrawer:")]
		partial void openBottomDrawer (Foundation.NSObject sender);

		[Foundation.Export("openLeftDrawer:")]
		partial void openLeftDrawer (Foundation.NSObject sender);

		[Foundation.Export("openLowerRightDrawer:")]
		partial void openLowerRightDrawer (Foundation.NSObject sender);

		[Foundation.Export("openUpperRightDrawer:")]
		partial void openUpperRightDrawer (Foundation.NSObject sender);

		[Foundation.Export("toggleBottomDrawer:")]
		partial void toggleBottomDrawer (Foundation.NSObject sender);

		[Foundation.Export("toggleLeftDrawer:")]
		partial void toggleLeftDrawer (Foundation.NSObject sender);

		[Foundation.Export("toggleLowerRightDrawer:")]
		partial void toggleLowerRightDrawer (Foundation.NSObject sender);

		[Foundation.Export("toggleUpperRightDrawer:")]
		partial void toggleUpperRightDrawer (Foundation.NSObject sender);

		[Foundation.Connect("leftDrawer")]
		private global::AppKit.NSDrawer leftDrawer {
			get {
				this.__mt_leftDrawer = ((global::AppKit.NSDrawer)(this.GetNativeField("leftDrawer")));
				return this.__mt_leftDrawer;
			}
			set {
				this.__mt_leftDrawer = value;
				this.SetNativeField("leftDrawer", value);
			}
		}
		
		[Foundation.Connect("lowerRightAllowClose")]
		private global::AppKit.NSButton lowerRightAllowClose {
			get {
				this.__mt_lowerRightAllowClose = ((global::AppKit.NSButton)(this.GetNativeField("lowerRightAllowClose")));
				return this.__mt_lowerRightAllowClose;
			}
			set {
				this.__mt_lowerRightAllowClose = value;
				this.SetNativeField("lowerRightAllowClose", value);
			}
		}
		
		[Foundation.Connect("myParentWindow")]
		private global::AppKit.NSWindow myParentWindow {
			get {
				this.__mt_myParentWindow = ((global::AppKit.NSWindow)(this.GetNativeField("myParentWindow")));
				return this.__mt_myParentWindow;
			}
			set {
				this.__mt_myParentWindow = value;
				this.SetNativeField("myParentWindow", value);
			}
		}
		
		[Foundation.Connect("upperRightAllowClose")]
		private global::AppKit.NSButton upperRightAllowClose {
			get {
				this.__mt_upperRightAllowClose = ((global::AppKit.NSButton)(this.GetNativeField("upperRightAllowClose")));
				return this.__mt_upperRightAllowClose;
			}
			set {
				this.__mt_upperRightAllowClose = value;
				this.SetNativeField("upperRightAllowClose", value);
			}
		}
	}
}
