// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NeHeLesson9 {
	
	
	// Should subclass MonoMac.AppKit.NSResponder
	[MonoMac.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
	}
	
	// Should subclass NSObject
	[MonoMac.Foundation.Register("FirstResponder")]
	public partial class FirstResponder {
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("toggleFullScreen:")]
		partial void toggleFullScreen (MonoMac.Foundation.NSObject sender);
}
}
