// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacDatabinding
{
	public partial class CollectionItemController : NSCollectionViewItem
	{
		public CollectionItemController (IntPtr handle) : base (handle)
		{
		}
	}
}
