// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacDatabinding
{
	public partial class OutlineViewController : NSViewController
	{
		#region Private Variables
		private NSMutableArray _people = new NSMutableArray();
		#endregion

		#region Computed Properties
		[Export("personModelArray")]
		public NSArray People {
			get { return _people; }
		}

		public PersonModel SelectedPerson { get; private set; }
		#endregion

		#region Constructors
		public OutlineViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Build list of employees
			var Craig = new PersonModel ("Craig Dunn", "Documentation Manager");
			Craig.AddPerson (new PersonModel ("Amy Burns", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Joel Martinez", "Web & Infrastructure"));
			Craig.AddPerson (new PersonModel ("Kevin Mullins", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Mark McLemore", "Technical Writer"));
			Craig.AddPerson (new PersonModel ("Tom Opgenorth", "Technical Writer"));
			AddPerson (Craig);

			var Larry = new PersonModel ("Larry O'Brien", "API Documentation Manager");
			Larry.AddPerson (new PersonModel ("Mike Norman", "API Documentor"));
			AddPerson (Larry);
		}

		public override void PrepareForSegue (NSStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			// Take action based on type
			switch (segue.Identifier) {
			case "EditorSegue":
				var editor = segue.DestinationController as PersonEditorViewController;
				editor.Presentor = this;
				editor.Person = SelectedPerson;
				break;
			}
		}
		#endregion

		#region Array Controller Methods
		[Export("addObject:")]
		public void AddPerson(PersonModel person) {
			WillChangeValue ("personModelArray");
			_people.Add (person);
			DidChangeValue ("personModelArray");
		}

		[Export("insertObject:inPersonModelArrayAtIndex:")]
		public void InsertPerson(PersonModel person, nint index) {
			WillChangeValue ("personModelArray");
			_people.Insert (person, index);
			DidChangeValue ("personModelArray");
		}

		[Export("removeObjectFromPersonModelArrayAtIndex:")]
		public void RemovePerson(nint index) {
			WillChangeValue ("personModelArray");
			_people.RemoveObject (index);
			DidChangeValue ("personModelArray");
		}

		[Export("setPersonModelArray:")]
		public void SetPeople(NSMutableArray array) {
			WillChangeValue ("personModelArray");
			_people = array;
			DidChangeValue ("personModelArray");
		}
		#endregion
	}
}
