// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacDatabinding
{
	public partial class PersonEditorViewController : NSViewController
	{
		#region Private Variables
		private PersonModel _person;
		#endregion

		#region Computed Properties
		[Export("Person")]
		public PersonModel Person {
			get { return _person; }
			set {
				WillChangeValue ("Person");
				_person = value;
				DidChangeValue ("Person");
			}
		}

		public bool isNew { get; set; } = false;
		public NSViewController Presentor { get; set; }
		#endregion

		#region Constructor
		public PersonEditorViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Private Methods
		private void CloseSheet() {
			Presentor.DismissViewController (this);
		}
		#endregion

		#region Actions
		partial void CancelClicked (Foundation.NSObject sender) {
			CloseSheet();
		}

		partial void OKClicked (Foundation.NSObject sender) {
			RaisePersonModified(Person);
			CloseSheet();
		}
		#endregion

		#region Events
		public delegate void PersonModifiedDelegate(PersonModel person);
		public event PersonModifiedDelegate PersonModified;

		internal void RaisePersonModified(PersonModel person) {
			if (this.PersonModified!=null) this.PersonModified(person);
		}
		#endregion
	}
}
