// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ImageKitDemo {
	
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::ImageKit.IKImageBrowserView __mt_browserView;
		
		#pragma warning disable 0169
		[Foundation.Export("AddButtonClicked:")]
		partial void AddButtonClicked (AppKit.NSButton sender);

		[Foundation.Export("SearchTextChanged:")]
		partial void SearchTextChanged (AppKit.NSSearchField sender);

		[Foundation.Export("SliderChanged:")]
		partial void SliderChanged (AppKit.NSSlider sender);

		[Foundation.Connect("browserView")]
		private global::ImageKit.IKImageBrowserView browserView {
			get {
				this.__mt_browserView = ((global::ImageKit.IKImageBrowserView)(this.GetNativeField("browserView")));
				return this.__mt_browserView;
			}
			set {
				this.__mt_browserView = value;
				this.SetNativeField("browserView", value);
			}
		}
	}
}
