// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GlossyClock {
	
	
	// Should subclass AppKit.NSView
	[Foundation.Register("ClockView")]
	public partial class ClockView {
	}
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
	}
}
