// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LayerBackedControls {
	
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::AppKit.NSButton __mt_rotatingButton;
		
		#pragma warning disable 0169
		[Foundation.Export("beep:")]
		partial void Beep (AppKit.NSButton sender);

		[Foundation.Export("rotateButton:")]
		partial void RotateButton (AppKit.NSButton sender);

		[Foundation.Connect("rotatingButton")]
		private global::AppKit.NSButton rotatingButton {
			get {
				this.__mt_rotatingButton = ((global::AppKit.NSButton)(this.GetNativeField("rotatingButton")));
				return this.__mt_rotatingButton;
			}
			set {
				this.__mt_rotatingButton = value;
				this.SetNativeField("rotatingButton", value);
			}
		}
	}
}
