// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LayerBackedControls {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSButton __mt_rotatingButton;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("beep:")]
		partial void Beep (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("rotateButton:")]
		partial void RotateButton (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("rotatingButton")]
		private global::MonoMac.AppKit.NSButton rotatingButton {
			get {
				this.__mt_rotatingButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("rotatingButton")));
				return this.__mt_rotatingButton;
			}
			set {
				this.__mt_rotatingButton = value;
				this.SetNativeField("rotatingButton", value);
			}
		}
	}
}
