// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacControls
{
	public partial class ButtonsViewController : NSViewController
	{
		#region Constructors
		public ButtonsViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			// Wireup events
			ButtonOutlet.Activated += (sender, e) => {
				FeedbackLabel.StringValue = "Button Outlet Pressed";
			};

			DisclosureButton.Activated += (sender, e) => {
				LorumIpsum.Hidden = (DisclosureButton.State == NSCellStateValue.On);
			};

			RoundedGradient.Activated += (sender, e) => {
				FeedbackLabel.StringValue = "Rounded Gradient Pressed";
			};
		}
		#endregion

		#region Button Action Handlers
		partial void ButtonAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Action Pressed";
		}

		partial void RecessedAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Recessed Pressed";
		}

		partial void RoundAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Round Pressed";
		}

		partial void RoundRectAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Round Rect Pressed";
		}

		partial void RoundTexturedAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Round Textured Pressed";
		}

		partial void SquareAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Square Pressed";
		}

		partial void TexturedAction (Foundation.NSObject sender) {
			FeedbackLabel.StringValue = "Button Textured Pressed";
		}
		#endregion
	}
}
