// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacControls
{
	public partial class CheckboxViewController : NSViewController
	{
		#region Constructors
		public CheckboxViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			// Wireup controls
			AdjustTime.Activated += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Adjust Time: {0}",AdjustTime.State == NSCellStateValue.On);
			};

			TransportationCar.Activated += (sender, e) => {
				FeedbackLabel.StringValue = "Car Selected";
			};

			TransportationPublic.Activated += (sender, e) => {
				FeedbackLabel.StringValue = "Public Selected";
			};

			TransportationWalking.Activated += (sender, e) => {
				FeedbackLabel.StringValue = "Walking Selected";
			};
		}
		#endregion

		#region Button Actions
		partial void SelectCar (Foundation.NSObject sender) {
			TransportationCar.State = NSCellStateValue.On;
			FeedbackLabel.StringValue = "Car Selected";
		}
		#endregion
	}
}
