// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacControls
{
	public partial class IndicatorViewController : NSViewController
	{
		#region Constructors
		public IndicatorViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			// Start animation on progress bars
			Indeterminate.StartAnimation (this);
			AsyncProgress.StartAnimation (this);

			// Wireup controls
			LevelIndicator.Activated += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Level: {0:###}",LevelIndicator.DoubleValue);
			};

			Rating.Activated += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Rating: {0:###}",Rating.DoubleValue);
			};

			Relevance.Activated += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Relevance: {0:###}",Relevance.DoubleValue);
			};
		}
		#endregion

		#region Actions
		partial void HundredPercent (Foundation.NSObject sender) {
			ProgressIndicator.DoubleValue = 100;
		}
		#endregion
	}
}
