// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace MacControls
{
	public partial class LeftViewController : NSViewController
	{
		#region Private Variables
		private SubviewType ViewType = SubviewType.None;
		#endregion

		#region Constructors
		public LeftViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Private Methods
		private void DisplaySubview(SubviewType type) {

			// Is this view already displayed?
			if (ViewType == type) return;

			// Save values
			ViewType = type;
			RaiseViewTypeChanged (type);
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();

			// Populate Source List
			SourceList.Initialize ();

			var TableViews = new SourceListItem ("Control Type");
			TableViews.AddItem ("Buttons", "tag.png", () => {
				DisplaySubview(SubviewType.Buttons);
			});
			TableViews.AddItem ("Checkboxes & Radio Buttons", "tag.png", () => {
				DisplaySubview(SubviewType.CheckAndRadioButtons);
			});
			TableViews.AddItem ("Menu Controls", "tag.png", () => {
				DisplaySubview(SubviewType.MenuControls);
			});
			TableViews.AddItem ("Selection Controls", "tag.png", () => {
				DisplaySubview(SubviewType.SelectionControls);
			});
			TableViews.AddItem ("Indicator Controls", "tag.png", () => {
				DisplaySubview(SubviewType.IndicatorControls);
			});
			TableViews.AddItem ("Text Controls", "tag.png", () => {
				DisplaySubview(SubviewType.TextControls);
			});
			TableViews.AddItem ("Content Views", "tag.png", () => {
				DisplaySubview(SubviewType.ContentViews);
			});
			SourceList.AddItem (TableViews);

			// Display Source List
			SourceList.ReloadData();
			SourceList.ExpandItem (null, true);
		}
		#endregion

		#region Events
		public delegate void ViewTypeChangedDelegate(SubviewType viewType);
		public event ViewTypeChangedDelegate ViewTypeChanged;

		internal void RaiseViewTypeChanged(SubviewType type) {
			if (this.ViewTypeChanged != null)
				this.ViewTypeChanged (type);
		}
		#endregion
	}
}
