// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacControls
{
	public partial class RightViewController : NSViewController
	{
		#region Constructors
		public RightViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Public Methods
		public void ShowView(SubviewType type) {

			// Take action based on requested type
			switch (type) {
			case SubviewType.Buttons:
				PerformSegue ("ButtonsSegue", this);
				break;
			case SubviewType.CheckAndRadioButtons:
				PerformSegue ("CheckboxSegue", this);
				break;
			case SubviewType.MenuControls:
				PerformSegue ("MenuSegue", this);
				break;
			case SubviewType.SelectionControls:
				PerformSegue ("SelectionSegue", this);
				break;
			case SubviewType.IndicatorControls:
				PerformSegue ("IndicatorSegue", this);
				break;
			case SubviewType.TextControls:
				PerformSegue ("TextSegue", this);
				break;
			case SubviewType.ContentViews:
				PerformSegue ("ContentSegue", this);
				break;
			}

		}
		#endregion
	}
}
