// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacControls
{
	public partial class TextViewController : NSViewController
	{
		#region Constructors
		public TextViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			// Wire-up controls
			UserField.EditingEnded += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("User ID: {0}",UserField.StringValue);
			};

			PasswordField.EditingEnded += (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Password: {0}",PasswordField.StringValue);
			};

			NumberField.EditingEnded+= (sender, e) => {
				FeedbackLabel.StringValue = string.Format("Number: {0}",NumberField.IntValue);
			};
		}
		#endregion
	}
}
