// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacMenus
{
	public partial class EditorWindowController : NSWindowController
	{
		public EditorWindowController (IntPtr handle) : base (handle)
		{
		}
	}
}
