// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacMenus
{
	public partial class PanelViewController : NSViewController
	{
		#region Constructor
		public PanelViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Custom Actions
		partial void propertyDocument (Foundation.NSObject sender) {
			propertyLabel.StringValue = "Document";
		}

		partial void propertyFont (Foundation.NSObject sender) {
			propertyLabel.StringValue = "Font";
		}

		partial void propertyText (Foundation.NSObject sender) {
			propertyLabel.StringValue = "Text";
		}
		#endregion
	}
}
