// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacWindows
{
	public partial class MasterWindowController : NSWindowController
	{
		public MasterWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad ()
		{
			base.WindowDidLoad ();

			Window.DidResize += (sender, e) => {
				// Do something as the window is being live resized
			};

			Window.DidEndLiveResize += (sender, e) => {
				// Do something after the user's finished resizing
				// the window
			};
		}
	}
}
