// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacWindows
{
	public partial class MasterWindowController : NSWindowController, INSWindowDelegate {
		public MasterWindowController (IntPtr handle) : base (handle)
		{
		}

		public override void WindowDidLoad ()
		{
			base.WindowDidLoad ();
			Window.Delegate = this;
		}

		[Export ("windowDidResize:")]
		public void DidResize (NSNotification notification)
		{
			// Do something as the window is being live resized
		}

		[Export ("windowDidEndLiveResize:")]
		public void DidEndLiveResize (NSNotification notification)
		{
			// Do something after the user's finished resizing
			// the window
		}
	}
}
