// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacWindows
{
	public partial class PreferencesViewController : NSViewController
	{
		#region Constructors
		public PreferencesViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion


	}
}
