// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacWindows
{
	public partial class PreferencesWindowController : NSWindowController
	{
		#region Computed Properties
		public PreferencesViewController ViewController {
			get { return Window.ContentViewController as PreferencesViewController; }
		}
		#endregion

		#region Constructors
		public PreferencesWindowController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void AwakeFromNib ()
		{
			base.AwakeFromNib ();


		}
		#endregion

	}
}
