// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace VillainTracker {
	
	
	// Should subclass MonoMac.AppKit.NSApplicationDelegate
	[MonoMac.Foundation.Register("VillainTrackerAppDelegate")]
	public partial class VillainTrackerAppDelegate {
		
		private global::MonoMac.AppKit.NSLevelIndicator __mt_evilnessView;
		
		private global::MonoMac.AppKit.NSTextField __mt_lastKnownLocationView;
		
		private global::MonoMac.AppKit.NSDatePicker __mt_lastSeenDateView;
		
		private global::MonoMac.AppKit.NSImageView __mt_mugshotView;
		
		private global::MonoMac.AppKit.NSTextField __mt_nameView;
		
		private global::MonoMac.AppKit.NSTextView __mt_notesView;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_powerSourceView;
		
		private global::MonoMac.AppKit.NSMatrix __mt_powersView;
		
		private global::MonoMac.AppKit.NSMatrix __mt_primaryMotivationView;
		
		private global::MonoMac.AppKit.NSComboBox __mt_swornEnemyView;
		
		private global::MonoMac.AppKit.NSTableView __mt_villainsTableView;
		
		private global::MonoMac.AppKit.NSWindow __mt_window;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("deleteVillain:")]
		partial void deleteVillain (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("newVillain:")]
		partial void newVillain (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeEvilness:")]
		partial void takeEvilness (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeLastKnownLocation:")]
		partial void takeLastKnownLocation (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeLastSeenDate:")]
		partial void takeLastSeenDate (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeMugshot:")]
		partial void takeMugshot (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeName:")]
		partial void takeName (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takePowerSource:")]
		partial void takePowerSource (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takePowers:")]
		partial void takePowers (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takePrimaryMotivation:")]
		partial void takePrimaryMotivation (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("takeSwornEnemy:")]
		partial void takeSwornEnemy (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Connect("evilnessView")]
		private global::MonoMac.AppKit.NSLevelIndicator evilnessView {
			get {
				this.__mt_evilnessView = ((global::MonoMac.AppKit.NSLevelIndicator)(this.GetNativeField("evilnessView")));
				return this.__mt_evilnessView;
			}
			set {
				this.__mt_evilnessView = value;
				this.SetNativeField("evilnessView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("lastKnownLocationView")]
		private global::MonoMac.AppKit.NSTextField lastKnownLocationView {
			get {
				this.__mt_lastKnownLocationView = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("lastKnownLocationView")));
				return this.__mt_lastKnownLocationView;
			}
			set {
				this.__mt_lastKnownLocationView = value;
				this.SetNativeField("lastKnownLocationView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("lastSeenDateView")]
		private global::MonoMac.AppKit.NSDatePicker lastSeenDateView {
			get {
				this.__mt_lastSeenDateView = ((global::MonoMac.AppKit.NSDatePicker)(this.GetNativeField("lastSeenDateView")));
				return this.__mt_lastSeenDateView;
			}
			set {
				this.__mt_lastSeenDateView = value;
				this.SetNativeField("lastSeenDateView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("mugshotView")]
		private global::MonoMac.AppKit.NSImageView mugshotView {
			get {
				this.__mt_mugshotView = ((global::MonoMac.AppKit.NSImageView)(this.GetNativeField("mugshotView")));
				return this.__mt_mugshotView;
			}
			set {
				this.__mt_mugshotView = value;
				this.SetNativeField("mugshotView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("nameView")]
		private global::MonoMac.AppKit.NSTextField nameView {
			get {
				this.__mt_nameView = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("nameView")));
				return this.__mt_nameView;
			}
			set {
				this.__mt_nameView = value;
				this.SetNativeField("nameView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("notesView")]
		private global::MonoMac.AppKit.NSTextView notesView {
			get {
				this.__mt_notesView = ((global::MonoMac.AppKit.NSTextView)(this.GetNativeField("notesView")));
				return this.__mt_notesView;
			}
			set {
				this.__mt_notesView = value;
				this.SetNativeField("notesView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("powerSourceView")]
		private global::MonoMac.AppKit.NSPopUpButton powerSourceView {
			get {
				this.__mt_powerSourceView = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("powerSourceView")));
				return this.__mt_powerSourceView;
			}
			set {
				this.__mt_powerSourceView = value;
				this.SetNativeField("powerSourceView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("powersView")]
		private global::MonoMac.AppKit.NSMatrix powersView {
			get {
				this.__mt_powersView = ((global::MonoMac.AppKit.NSMatrix)(this.GetNativeField("powersView")));
				return this.__mt_powersView;
			}
			set {
				this.__mt_powersView = value;
				this.SetNativeField("powersView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("primaryMotivationView")]
		private global::MonoMac.AppKit.NSMatrix primaryMotivationView {
			get {
				this.__mt_primaryMotivationView = ((global::MonoMac.AppKit.NSMatrix)(this.GetNativeField("primaryMotivationView")));
				return this.__mt_primaryMotivationView;
			}
			set {
				this.__mt_primaryMotivationView = value;
				this.SetNativeField("primaryMotivationView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("swornEnemyView")]
		private global::MonoMac.AppKit.NSComboBox swornEnemyView {
			get {
				this.__mt_swornEnemyView = ((global::MonoMac.AppKit.NSComboBox)(this.GetNativeField("swornEnemyView")));
				return this.__mt_swornEnemyView;
			}
			set {
				this.__mt_swornEnemyView = value;
				this.SetNativeField("swornEnemyView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("villainsTableView")]
		private global::MonoMac.AppKit.NSTableView villainsTableView {
			get {
				this.__mt_villainsTableView = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("villainsTableView")));
				return this.__mt_villainsTableView;
			}
			set {
				this.__mt_villainsTableView = value;
				this.SetNativeField("villainsTableView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("window")]
		private global::MonoMac.AppKit.NSWindow window {
			get {
				this.__mt_window = ((global::MonoMac.AppKit.NSWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
	}
}
