// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Fire {
	
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::AppKit.NSSlider __mt_gasSlider;
		
		private global::AppKit.NSView __mt_view;
		
		#pragma warning disable 0169
		[Foundation.Export("slidersChanged:")]
		partial void slidersChanged (Foundation.NSObject sender);

		[Foundation.Connect("gasSlider")]
		private global::AppKit.NSSlider gasSlider {
			get {
				this.__mt_gasSlider = ((global::AppKit.NSSlider)(this.GetNativeField("gasSlider")));
				return this.__mt_gasSlider;
			}
			set {
				this.__mt_gasSlider = value;
				this.SetNativeField("gasSlider", value);
			}
		}
		
		[Foundation.Connect("view")]
		private global::AppKit.NSView view {
			get {
				this.__mt_view = ((global::AppKit.NSView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
	}
}
