// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PopupBindings {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("TestWindow")]
	public partial class TestWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("TestWindowController")]
	public partial class TestWindowController {
		
		private global::MonoMac.AppKit.NSArrayController __mt_arrayController;
		
		private global::MonoMac.Foundation.NSObject __mt_name;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Connect("arrayController")]
		private global::MonoMac.AppKit.NSArrayController arrayController {
			get {
				this.__mt_arrayController = ((global::MonoMac.AppKit.NSArrayController)(this.GetNativeField("arrayController")));
				return this.__mt_arrayController;
			}
			set {
				this.__mt_arrayController = value;
				this.SetNativeField("arrayController", value);
			}
		}
		
		[MonoMac.Foundation.Connect("name")]
		private global::MonoMac.Foundation.NSObject name {
			get {
				this.__mt_name = ((global::MonoMac.Foundation.NSObject)(this.GetNativeField("name")));
				return this.__mt_name;
			}
			set {
				this.__mt_name = value;
				this.SetNativeField("name", value);
			}
		}
	}
}
