// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DockAppIcon {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSButton __mt_badgeCheck;
		
		private global::MonoMac.AppKit.NSTextField __mt_badgeNumber;
		
		private global::MonoMac.AppKit.NSTextField __mt_customFormat;
		
		private global::MonoMac.AppKit.NSButton __mt_formatCheck;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_popupRequestType;
		
		private global::MonoMac.AppKit.NSButton __mt_showAppBadgeCheck;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("badgeCheckAction:")]
		partial void badgeCheckAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("customFormatAction:")]
		partial void customFormatAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("requestAction:")]
		partial void requestAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("showAppBadgeAction:")]
		partial void showAppBadgeAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("stepperAction:")]
		partial void stepperAction (MonoMac.AppKit.NSStepper sender);

		[MonoMac.Foundation.Connect("badgeCheck")]
		private global::MonoMac.AppKit.NSButton badgeCheck {
			get {
				this.__mt_badgeCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("badgeCheck")));
				return this.__mt_badgeCheck;
			}
			set {
				this.__mt_badgeCheck = value;
				this.SetNativeField("badgeCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("badgeNumber")]
		private global::MonoMac.AppKit.NSTextField badgeNumber {
			get {
				this.__mt_badgeNumber = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("badgeNumber")));
				return this.__mt_badgeNumber;
			}
			set {
				this.__mt_badgeNumber = value;
				this.SetNativeField("badgeNumber", value);
			}
		}
		
		[MonoMac.Foundation.Connect("customFormat")]
		private global::MonoMac.AppKit.NSTextField customFormat {
			get {
				this.__mt_customFormat = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("customFormat")));
				return this.__mt_customFormat;
			}
			set {
				this.__mt_customFormat = value;
				this.SetNativeField("customFormat", value);
			}
		}
		
		[MonoMac.Foundation.Connect("formatCheck")]
		private global::MonoMac.AppKit.NSButton formatCheck {
			get {
				this.__mt_formatCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("formatCheck")));
				return this.__mt_formatCheck;
			}
			set {
				this.__mt_formatCheck = value;
				this.SetNativeField("formatCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("popupRequestType")]
		private global::MonoMac.AppKit.NSPopUpButton popupRequestType {
			get {
				this.__mt_popupRequestType = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("popupRequestType")));
				return this.__mt_popupRequestType;
			}
			set {
				this.__mt_popupRequestType = value;
				this.SetNativeField("popupRequestType", value);
			}
		}
		
		[MonoMac.Foundation.Connect("showAppBadgeCheck")]
		private global::MonoMac.AppKit.NSButton showAppBadgeCheck {
			get {
				this.__mt_showAppBadgeCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("showAppBadgeCheck")));
				return this.__mt_showAppBadgeCheck;
			}
			set {
				this.__mt_showAppBadgeCheck = value;
				this.SetNativeField("showAppBadgeCheck", value);
			}
		}
	}
}
