// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TwoMinuteGrowler {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSTextField __mt_countDownLabel;
		
		private global::MonoMac.AppKit.NSButton __mt_startStopButton;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("startStopAction:")]
		partial void startStopAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("countDownLabel")]
		private global::MonoMac.AppKit.NSTextField countDownLabel {
			get {
				this.__mt_countDownLabel = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("countDownLabel")));
				return this.__mt_countDownLabel;
			}
			set {
				this.__mt_countDownLabel = value;
				this.SetNativeField("countDownLabel", value);
			}
		}
		
		[MonoMac.Foundation.Connect("startStopButton")]
		private global::MonoMac.AppKit.NSButton startStopButton {
			get {
				this.__mt_startStopButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("startStopButton")));
				return this.__mt_startStopButton;
			}
			set {
				this.__mt_startStopButton = value;
				this.SetNativeField("startStopButton", value);
			}
		}
	}
}
