// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SearchField {
	
	
	// Should subclass AppKit.NSWindow
	[Foundation.Register("SearchFieldWindow")]
	public partial class SearchFieldWindow {
	}
	
	// Should subclass AppKit.NSWindowController
	[Foundation.Register("SearchFieldWindowController")]
	public partial class SearchFieldWindowController {
		
		private global::AppKit.NSSearchField __mt_searchField;
		
		private global::AppKit.NSWindow __mt_simpleSheet;
		
		#pragma warning disable 0169
		[Foundation.Export("sheetDone:")]
		partial void sheetDone (AppKit.NSButton sender);

		[Foundation.Connect("searchField")]
		private global::AppKit.NSSearchField searchField {
			get {
				this.__mt_searchField = ((global::AppKit.NSSearchField)(this.GetNativeField("searchField")));
				return this.__mt_searchField;
			}
			set {
				this.__mt_searchField = value;
				this.SetNativeField("searchField", value);
			}
		}
		
		[Foundation.Connect("simpleSheet")]
		private global::AppKit.NSWindow simpleSheet {
			get {
				this.__mt_simpleSheet = ((global::AppKit.NSWindow)(this.GetNativeField("simpleSheet")));
				return this.__mt_simpleSheet;
			}
			set {
				this.__mt_simpleSheet = value;
				this.SetNativeField("simpleSheet", value);
			}
		}
	}
}
