// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace MacImages
{
	public partial class TableViewController : NSViewController
	{
		#region Constructors
		public TableViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			// Create the Product Table Data Source and populate it
			var DataSource = new ProductTableDataSource ();
			DataSource.Products.Add (new Product ("Xamarin.iOS", "Allows you to develop native iOS Applications in C#"));
			DataSource.Products.Add (new Product ("Xamarin.Android", "Allows you to develop native Android Applications in C#"));
			DataSource.Products.Add (new Product ("Xamarin.Mac", "Allows you to develop Mac native Applications in C#"));
			DataSource.Sort ("Title", true);

			// Populate the Product Table
			ProductTable.DataSource = DataSource;
			ProductTable.Delegate = new ProductTableDelegate (DataSource);

			// Auto select the first row
			ProductTable.SelectRow (0, false);
		}
		#endregion
	}
}
