// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CoreWLANWirelessManager {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
		
		private global::MonoMac.AppKit.NSTextField __mt_bssidField;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_channelPopup;
		
		private global::MonoMac.AppKit.NSTextField __mt_countryCodeField;
		
		private global::MonoMac.AppKit.NSButton __mt_disconnectButton;
		
		private global::MonoMac.AppKit.NSButton __mt_ibssCancelButton;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_ibssChannelPopupButton;
		
		private global::MonoMac.AppKit.NSWindow __mt_ibssDialogWindow;
		
		private global::MonoMac.AppKit.NSTextField __mt_ibssNetworkNameField;
		
		private global::MonoMac.AppKit.NSButton __mt_ibssOKButton;
		
		private global::MonoMac.AppKit.NSTextField __mt_ibssPassphraseField;
		
		private global::MonoMac.AppKit.NSProgressIndicator __mt_ibssSpinner;
		
		private global::MonoMac.AppKit.NSButton __mt_joinButton;
		
		private global::MonoMac.AppKit.NSButton __mt_joinCancelButton;
		
		private global::MonoMac.AppKit.NSWindow __mt_joinDialogWindow;
		
		private global::MonoMac.AppKit.NSTextField __mt_joinNetworkNameField;
		
		private global::MonoMac.AppKit.NSButton __mt_joinOKButton;
		
		private global::MonoMac.AppKit.NSTextField __mt_joinPassphraseField;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_joinSecurityPopupButton;
		
		private global::MonoMac.AppKit.NSProgressIndicator __mt_joinSpinner;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_joinUser8021XProfilePopupButton;
		
		private global::MonoMac.AppKit.NSTextField __mt_joinUsernameField;
		
		private global::MonoMac.AppKit.NSWindow __mt_mainWindow;
		
		private global::MonoMac.AppKit.NSButton __mt_mergeScanResultsCheckbox;
		
		private global::MonoMac.AppKit.NSTextField __mt_noiseField;
		
		private global::MonoMac.AppKit.NSTextField __mt_opModeField;
		
		private global::MonoMac.AppKit.NSTextField __mt_phyModeField;
		
		private global::MonoMac.AppKit.NSSegmentedControl __mt_powerStateControl;
		
		private global::MonoMac.AppKit.NSButton __mt_refreshButton;
		
		private global::MonoMac.AppKit.NSProgressIndicator __mt_refreshSpinner;
		
		private global::MonoMac.AppKit.NSTextField __mt_rssiField;
		
		private global::MonoMac.AppKit.NSTableView __mt_scanResultsTable;
		
		private global::MonoMac.AppKit.NSTextField __mt_securityModeField;
		
		private global::MonoMac.AppKit.NSTextField __mt_ssidField;
		
		private global::MonoMac.AppKit.NSTextField __mt_supportedChannelsField;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_supportedInterfacesPopup;
		
		private global::MonoMac.AppKit.NSTextField __mt_supportedPHYModes;
		
		private global::MonoMac.AppKit.NSTabView __mt_tabView;
		
		private global::MonoMac.AppKit.NSTextField __mt_txPowerField;
		
		private global::MonoMac.AppKit.NSTextField __mt_txRateField;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("change8021XProfile:")]
		partial void change8021XProfile (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("changeChannel:")]
		partial void changeChannel (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("changePower:")]
		partial void changePower (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("changeSecurityMode:")]
		partial void changeSecurityMode (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("createIBSSButtonPressed:")]
		partial void createIBSSButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("disconnect:")]
		partial void disconnect (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("ibssCancelButtonPressed:")]
		partial void ibssCancelButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("ibssOKButtonPressed:")]
		partial void ibssOKButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("interfaceSelected:")]
		partial void interfaceSelected (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("joinButtonPressed:")]
		partial void joinButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("joinCancelButtonPressed:")]
		partial void joinCancelButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("joinOKButtonPressed:")]
		partial void joinOKButtonPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Export("refreshPressed:")]
		partial void refreshPressed (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Connect("bssidField")]
		private global::MonoMac.AppKit.NSTextField bssidField {
			get {
				this.__mt_bssidField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("bssidField")));
				return this.__mt_bssidField;
			}
			set {
				this.__mt_bssidField = value;
				this.SetNativeField("bssidField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("channelPopup")]
		private global::MonoMac.AppKit.NSPopUpButton channelPopup {
			get {
				this.__mt_channelPopup = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("channelPopup")));
				return this.__mt_channelPopup;
			}
			set {
				this.__mt_channelPopup = value;
				this.SetNativeField("channelPopup", value);
			}
		}
		
		[MonoMac.Foundation.Connect("countryCodeField")]
		private global::MonoMac.AppKit.NSTextField countryCodeField {
			get {
				this.__mt_countryCodeField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("countryCodeField")));
				return this.__mt_countryCodeField;
			}
			set {
				this.__mt_countryCodeField = value;
				this.SetNativeField("countryCodeField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("disconnectButton")]
		private global::MonoMac.AppKit.NSButton disconnectButton {
			get {
				this.__mt_disconnectButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("disconnectButton")));
				return this.__mt_disconnectButton;
			}
			set {
				this.__mt_disconnectButton = value;
				this.SetNativeField("disconnectButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssCancelButton")]
		private global::MonoMac.AppKit.NSButton ibssCancelButton {
			get {
				this.__mt_ibssCancelButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("ibssCancelButton")));
				return this.__mt_ibssCancelButton;
			}
			set {
				this.__mt_ibssCancelButton = value;
				this.SetNativeField("ibssCancelButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssChannelPopupButton")]
		private global::MonoMac.AppKit.NSPopUpButton ibssChannelPopupButton {
			get {
				this.__mt_ibssChannelPopupButton = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("ibssChannelPopupButton")));
				return this.__mt_ibssChannelPopupButton;
			}
			set {
				this.__mt_ibssChannelPopupButton = value;
				this.SetNativeField("ibssChannelPopupButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssDialogWindow")]
		private global::MonoMac.AppKit.NSWindow ibssDialogWindow {
			get {
				this.__mt_ibssDialogWindow = ((global::MonoMac.AppKit.NSWindow)(this.GetNativeField("ibssDialogWindow")));
				return this.__mt_ibssDialogWindow;
			}
			set {
				this.__mt_ibssDialogWindow = value;
				this.SetNativeField("ibssDialogWindow", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssNetworkNameField")]
		private global::MonoMac.AppKit.NSTextField ibssNetworkNameField {
			get {
				this.__mt_ibssNetworkNameField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("ibssNetworkNameField")));
				return this.__mt_ibssNetworkNameField;
			}
			set {
				this.__mt_ibssNetworkNameField = value;
				this.SetNativeField("ibssNetworkNameField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssOKButton")]
		private global::MonoMac.AppKit.NSButton ibssOKButton {
			get {
				this.__mt_ibssOKButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("ibssOKButton")));
				return this.__mt_ibssOKButton;
			}
			set {
				this.__mt_ibssOKButton = value;
				this.SetNativeField("ibssOKButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssPassphraseField")]
		private global::MonoMac.AppKit.NSTextField ibssPassphraseField {
			get {
				this.__mt_ibssPassphraseField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("ibssPassphraseField")));
				return this.__mt_ibssPassphraseField;
			}
			set {
				this.__mt_ibssPassphraseField = value;
				this.SetNativeField("ibssPassphraseField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ibssSpinner")]
		private global::MonoMac.AppKit.NSProgressIndicator ibssSpinner {
			get {
				this.__mt_ibssSpinner = ((global::MonoMac.AppKit.NSProgressIndicator)(this.GetNativeField("ibssSpinner")));
				return this.__mt_ibssSpinner;
			}
			set {
				this.__mt_ibssSpinner = value;
				this.SetNativeField("ibssSpinner", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinButton")]
		private global::MonoMac.AppKit.NSButton joinButton {
			get {
				this.__mt_joinButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("joinButton")));
				return this.__mt_joinButton;
			}
			set {
				this.__mt_joinButton = value;
				this.SetNativeField("joinButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinCancelButton")]
		private global::MonoMac.AppKit.NSButton joinCancelButton {
			get {
				this.__mt_joinCancelButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("joinCancelButton")));
				return this.__mt_joinCancelButton;
			}
			set {
				this.__mt_joinCancelButton = value;
				this.SetNativeField("joinCancelButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinDialogWindow")]
		private global::MonoMac.AppKit.NSWindow joinDialogWindow {
			get {
				this.__mt_joinDialogWindow = ((global::MonoMac.AppKit.NSWindow)(this.GetNativeField("joinDialogWindow")));
				return this.__mt_joinDialogWindow;
			}
			set {
				this.__mt_joinDialogWindow = value;
				this.SetNativeField("joinDialogWindow", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinNetworkNameField")]
		private global::MonoMac.AppKit.NSTextField joinNetworkNameField {
			get {
				this.__mt_joinNetworkNameField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("joinNetworkNameField")));
				return this.__mt_joinNetworkNameField;
			}
			set {
				this.__mt_joinNetworkNameField = value;
				this.SetNativeField("joinNetworkNameField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinOKButton")]
		private global::MonoMac.AppKit.NSButton joinOKButton {
			get {
				this.__mt_joinOKButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("joinOKButton")));
				return this.__mt_joinOKButton;
			}
			set {
				this.__mt_joinOKButton = value;
				this.SetNativeField("joinOKButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinPassphraseField")]
		private global::MonoMac.AppKit.NSTextField joinPassphraseField {
			get {
				this.__mt_joinPassphraseField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("joinPassphraseField")));
				return this.__mt_joinPassphraseField;
			}
			set {
				this.__mt_joinPassphraseField = value;
				this.SetNativeField("joinPassphraseField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinSecurityPopupButton")]
		private global::MonoMac.AppKit.NSPopUpButton joinSecurityPopupButton {
			get {
				this.__mt_joinSecurityPopupButton = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("joinSecurityPopupButton")));
				return this.__mt_joinSecurityPopupButton;
			}
			set {
				this.__mt_joinSecurityPopupButton = value;
				this.SetNativeField("joinSecurityPopupButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinSpinner")]
		private global::MonoMac.AppKit.NSProgressIndicator joinSpinner {
			get {
				this.__mt_joinSpinner = ((global::MonoMac.AppKit.NSProgressIndicator)(this.GetNativeField("joinSpinner")));
				return this.__mt_joinSpinner;
			}
			set {
				this.__mt_joinSpinner = value;
				this.SetNativeField("joinSpinner", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinUser8021XProfilePopupButton")]
		private global::MonoMac.AppKit.NSPopUpButton joinUser8021XProfilePopupButton {
			get {
				this.__mt_joinUser8021XProfilePopupButton = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("joinUser8021XProfilePopupButton")));
				return this.__mt_joinUser8021XProfilePopupButton;
			}
			set {
				this.__mt_joinUser8021XProfilePopupButton = value;
				this.SetNativeField("joinUser8021XProfilePopupButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("joinUsernameField")]
		private global::MonoMac.AppKit.NSTextField joinUsernameField {
			get {
				this.__mt_joinUsernameField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("joinUsernameField")));
				return this.__mt_joinUsernameField;
			}
			set {
				this.__mt_joinUsernameField = value;
				this.SetNativeField("joinUsernameField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("mainWindow")]
		private global::MonoMac.AppKit.NSWindow mainWindow {
			get {
				this.__mt_mainWindow = ((global::MonoMac.AppKit.NSWindow)(this.GetNativeField("mainWindow")));
				return this.__mt_mainWindow;
			}
			set {
				this.__mt_mainWindow = value;
				this.SetNativeField("mainWindow", value);
			}
		}
		
		[MonoMac.Foundation.Connect("mergeScanResultsCheckbox")]
		private global::MonoMac.AppKit.NSButton mergeScanResultsCheckbox {
			get {
				this.__mt_mergeScanResultsCheckbox = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("mergeScanResultsCheckbox")));
				return this.__mt_mergeScanResultsCheckbox;
			}
			set {
				this.__mt_mergeScanResultsCheckbox = value;
				this.SetNativeField("mergeScanResultsCheckbox", value);
			}
		}
		
		[MonoMac.Foundation.Connect("noiseField")]
		private global::MonoMac.AppKit.NSTextField noiseField {
			get {
				this.__mt_noiseField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("noiseField")));
				return this.__mt_noiseField;
			}
			set {
				this.__mt_noiseField = value;
				this.SetNativeField("noiseField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("opModeField")]
		private global::MonoMac.AppKit.NSTextField opModeField {
			get {
				this.__mt_opModeField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("opModeField")));
				return this.__mt_opModeField;
			}
			set {
				this.__mt_opModeField = value;
				this.SetNativeField("opModeField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("phyModeField")]
		private global::MonoMac.AppKit.NSTextField phyModeField {
			get {
				this.__mt_phyModeField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("phyModeField")));
				return this.__mt_phyModeField;
			}
			set {
				this.__mt_phyModeField = value;
				this.SetNativeField("phyModeField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("powerStateControl")]
		private global::MonoMac.AppKit.NSSegmentedControl powerStateControl {
			get {
				this.__mt_powerStateControl = ((global::MonoMac.AppKit.NSSegmentedControl)(this.GetNativeField("powerStateControl")));
				return this.__mt_powerStateControl;
			}
			set {
				this.__mt_powerStateControl = value;
				this.SetNativeField("powerStateControl", value);
			}
		}
		
		[MonoMac.Foundation.Connect("refreshButton")]
		private global::MonoMac.AppKit.NSButton refreshButton {
			get {
				this.__mt_refreshButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("refreshButton")));
				return this.__mt_refreshButton;
			}
			set {
				this.__mt_refreshButton = value;
				this.SetNativeField("refreshButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("refreshSpinner")]
		private global::MonoMac.AppKit.NSProgressIndicator refreshSpinner {
			get {
				this.__mt_refreshSpinner = ((global::MonoMac.AppKit.NSProgressIndicator)(this.GetNativeField("refreshSpinner")));
				return this.__mt_refreshSpinner;
			}
			set {
				this.__mt_refreshSpinner = value;
				this.SetNativeField("refreshSpinner", value);
			}
		}
		
		[MonoMac.Foundation.Connect("rssiField")]
		private global::MonoMac.AppKit.NSTextField rssiField {
			get {
				this.__mt_rssiField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("rssiField")));
				return this.__mt_rssiField;
			}
			set {
				this.__mt_rssiField = value;
				this.SetNativeField("rssiField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("scanResultsTable")]
		private global::MonoMac.AppKit.NSTableView scanResultsTable {
			get {
				this.__mt_scanResultsTable = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("scanResultsTable")));
				return this.__mt_scanResultsTable;
			}
			set {
				this.__mt_scanResultsTable = value;
				this.SetNativeField("scanResultsTable", value);
			}
		}
		
		[MonoMac.Foundation.Connect("securityModeField")]
		private global::MonoMac.AppKit.NSTextField securityModeField {
			get {
				this.__mt_securityModeField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("securityModeField")));
				return this.__mt_securityModeField;
			}
			set {
				this.__mt_securityModeField = value;
				this.SetNativeField("securityModeField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("ssidField")]
		private global::MonoMac.AppKit.NSTextField ssidField {
			get {
				this.__mt_ssidField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("ssidField")));
				return this.__mt_ssidField;
			}
			set {
				this.__mt_ssidField = value;
				this.SetNativeField("ssidField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("supportedChannelsField")]
		private global::MonoMac.AppKit.NSTextField supportedChannelsField {
			get {
				this.__mt_supportedChannelsField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("supportedChannelsField")));
				return this.__mt_supportedChannelsField;
			}
			set {
				this.__mt_supportedChannelsField = value;
				this.SetNativeField("supportedChannelsField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("supportedInterfacesPopup")]
		private global::MonoMac.AppKit.NSPopUpButton supportedInterfacesPopup {
			get {
				this.__mt_supportedInterfacesPopup = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("supportedInterfacesPopup")));
				return this.__mt_supportedInterfacesPopup;
			}
			set {
				this.__mt_supportedInterfacesPopup = value;
				this.SetNativeField("supportedInterfacesPopup", value);
			}
		}
		
		[MonoMac.Foundation.Connect("supportedPHYModes")]
		private global::MonoMac.AppKit.NSTextField supportedPHYModes {
			get {
				this.__mt_supportedPHYModes = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("supportedPHYModes")));
				return this.__mt_supportedPHYModes;
			}
			set {
				this.__mt_supportedPHYModes = value;
				this.SetNativeField("supportedPHYModes", value);
			}
		}
		
		[MonoMac.Foundation.Connect("tabView")]
		private global::MonoMac.AppKit.NSTabView tabView {
			get {
				this.__mt_tabView = ((global::MonoMac.AppKit.NSTabView)(this.GetNativeField("tabView")));
				return this.__mt_tabView;
			}
			set {
				this.__mt_tabView = value;
				this.SetNativeField("tabView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("txPowerField")]
		private global::MonoMac.AppKit.NSTextField txPowerField {
			get {
				this.__mt_txPowerField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("txPowerField")));
				return this.__mt_txPowerField;
			}
			set {
				this.__mt_txPowerField = value;
				this.SetNativeField("txPowerField", value);
			}
		}
		
		[MonoMac.Foundation.Connect("txRateField")]
		private global::MonoMac.AppKit.NSTextField txRateField {
			get {
				this.__mt_txRateField = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("txRateField")));
				return this.__mt_txRateField;
			}
			set {
				this.__mt_txRateField = value;
				this.SetNativeField("txRateField", value);
			}
		}
	}
}
