// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CAQuartzComposition {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("MainWindow")]
	public partial class MainWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("MainWindowController")]
	public partial class MainWindowController {
	}
	
	// Should subclass MonoMac.AppKit.NSView
	[MonoMac.Foundation.Register("MyQuartzView")]
	public partial class MyQuartzView {
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("filterSwitch:")]
		partial void filterSwitch (MonoMac.AppKit.NSMenuItem sender);

		[MonoMac.Foundation.Export("switchView:")]
		partial void switchView (MonoMac.AppKit.NSMenuItem sender);
}
}
