// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// Handles the View that is displayed inside the <see cref="SourceWriter.AboutWindowController"/>
	/// </summary>
	public partial class AboutViewController : NSViewController
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.AboutViewController"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public AboutViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Actions
		/// <summary>
		/// Displays the license for the Icons8 icons when the license label is clicked.
		/// </summary>
		/// <param name="sender">Sender.</param>
		partial void IconsClicked (Foundation.NSObject sender) {

			NSWorkspace.SharedWorkspace.OpenUrl(NSUrl.FromString("https://icons8.com/license/"));

		}
		#endregion
	}
}
