// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// Controls the custom About Window that is displayed when the user selects the About SourceWriter
	/// Menu Item from the SourceWriter Menu.
	/// </summary>
	public partial class AboutWindowController : NSWindowController
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.AboutWindowController"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public AboutWindowController (IntPtr handle) : base (handle)
		{
		}
		#endregion
	}
}
