// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// Definition view used to display information about a selected <see cref="AppKit.TextKit.Formatter.KeywordDescriptor"/> 
	/// currently selected in the document editor.
	/// </summary>
	public partial class DefinitionView : NSView
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.DefinitionView"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public DefinitionView (IntPtr handle) : base (handle)
		{
		}
		#endregion
	}
}
