// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// This controller handles the general user preferences for the app.
	/// </summary>
	/// <remarks>This section uses Data Binding and Key-Value Coding to bind
	/// preference values to UI Controls on the Storyboard. For more information
	/// see: http://developer.xamarin.com/guides/mac/application_fundamentals/databinding/</remarks>
	public partial class GeneralPrefsController : NSViewController
	{
		#region Application Access
		/// <summary>
		/// A helper shortcut to the app delegate.
		/// </summary>
		/// <value>The app.</value>
		public static AppDelegate App {
			get { return (AppDelegate)NSApplication.SharedApplication.Delegate; }
		}
		#endregion

		#region Computed Properties
		/// <summary>
		/// Gets the system-wide preferences for the app.
		/// </summary>
		/// <value>The system-wide <see cref="SourceWriter.AppPreferences"/>.</value>
		/// <remarks>This property is configured for data binding the values to fields in the
		/// Storyboard UI design.</remarks>
		[Export("Preferences")]
		public AppPreferences Preferences {
			get { return App.Preferences; }
		}
		#endregion

		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.GeneralPrefsController"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public GeneralPrefsController (IntPtr handle) : base (handle)
		{
		}
		#endregion
	}
}
