// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// Controls the User Preferences window that allows the user to set their 
	/// preferences for the app.
	/// </summary>
	public partial class PreferenceWindowController : NSWindowController
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.PreferenceWindowController"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public PreferenceWindowController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		/// <summary>
		/// Called when the window is loaded from the Storyboard.
		/// </summary>
		public override void WindowDidLoad ()
		{
			base.WindowDidLoad ();

			// Initialize
			Window.Delegate = new PreferenceWidowDelegate(Window);
			Toolbar.SelectedItemIdentifier = "General";
		}
		#endregion
	}
}
