// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// The <see cref="SourceWriter.TemplateWindowController"/> manages the Window that 
	/// handles the creation of a new document based on the user's selection.
	/// </summary>
	public partial class TemplateWindowController : NSWindowController
	{
		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.TemplateWindowController"/> class.
		/// </summary>
		/// <param name="handle">An <c>Intptr</c>.</param>
		public TemplateWindowController (IntPtr handle) : base (handle)
		{
		}
		#endregion
	
	}
}
