// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SourceWriter
{
	/// <summary>
	/// The <see cref="SourceWriter.TemplateViewController"/> handles the creation of a new document
	/// based on the user's selection.
	/// </summary>
	public partial class TemplateViewController : NSViewController
	{
		#region Application Access
		/// <summary>
		/// A helper shortcut to the app delegate.
		/// </summary>
		/// <value>The app.</value>
		public static AppDelegate App {
			get { return (AppDelegate)NSApplication.SharedApplication.Delegate; }
		}
		#endregion

		#region Computed Properties
		/// <summary>
		/// Gets or sets the default language that the <see cref="SourceWriter.ViewController"/> will
		/// be editing.
		/// </summary>
		/// <value>An integer representing the default language as: 0 - C#,
		/// 1 - HTML, 2 - MarkDown, 3 - XML.</value>
		public int DefaultLanguage { get; set; } = App.Preferences.DefaultLanguage;
		#endregion

		#region Constructors
		/// <summary>
		/// Initializes a new instance of the <see cref="SourceWriter.TemplateViewController"/> class.
		/// </summary>
		/// <param name="handle">Handle.</param>
		public TemplateViewController (IntPtr handle) : base (handle)
		{
		}
		#endregion

		#region Override Methods
		/// <summary>
		/// This method is called before the View will be displayed to the screen.
		/// </summary>
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			// Auto Select the default language
			switch (DefaultLanguage) {
			case 0:
				CSharpFile.Bordered = true;
				break;
			case 1:
				HTMLFile.Bordered = true;
				break;
			case 2:
				MarkDownFile.Bordered = true;
				break;
			case 3:
				XMLFile.Bordered = true;
				break;
			}

		}

		/// <summary>
		/// The method is called before a segue is launched so that it can be configured.
		/// </summary>
		/// <param name="segue">The segue being started.</param>
		/// <param name="sender">The object starting the segue.</param>
		public override void PrepareForSegue (NSStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			// Take action based on the segue type
			switch (segue.Identifier) {
			case "OpenEditorSegue":
				// Inform window of its type
				var controller = segue.DestinationController as EditorWindowController;
				controller.ContentController.DefaultLanguage = DefaultLanguage;
				break;
			}
		}
		#endregion

		#region Actions
		/// <summary>
		/// Determines whether this instance cancel new document requested by the sender.
		/// </summary>
		/// <returns><c>true</c> if this instance cancel new document the specified sender; otherwise, <c>false</c>.</returns>
		/// <param name="sender">The object that started this action.</param>
		partial void CancelNewDocument (Foundation.NSObject sender) {
			// Close this window
			View.Window.PerformClose(this);
		}

		/// <summary>
		/// Selects C sharp as the new document language.
		/// </summary>
		/// <param name="sender">The object that started this action.</param>
		partial void SelectCSharp (Foundation.NSObject sender) {

			// Update UI
			CSharpFile.Bordered = true;
			HTMLFile.Bordered = false;
			MarkDownFile.Bordered = false;
			XMLFile.Bordered = false;

			// Save selection
			DefaultLanguage = 0;
		}

		/// <summary>
		/// Selects HTML as the new document language.
		/// </summary>
		/// <param name="sender">The object that started this action.</param>
		partial void SelectHTML (Foundation.NSObject sender) {

			// Update UI
			CSharpFile.Bordered = false;
			HTMLFile.Bordered = true;
			MarkDownFile.Bordered = false;
			XMLFile.Bordered = false;

			// Save selection
			DefaultLanguage = 1;
		}

		/// <summary>
		/// Selects MarkDown as the new document language.
		/// </summary>
		/// <param name="sender">The object that started this action.</param>
		partial void SelectMarkDown (Foundation.NSObject sender) {

			// Update UI
			CSharpFile.Bordered = false;
			HTMLFile.Bordered = false;
			MarkDownFile.Bordered = true;
			XMLFile.Bordered = false;

			// Save selection
			DefaultLanguage = 2;
		}

		/// <summary>
		/// Selects XML as the new document language.
		/// </summary>
		/// <param name="sender">The object that started this action.</param>
		partial void SelectXML (Foundation.NSObject sender) {

			// Update UI
			CSharpFile.Bordered = false;
			HTMLFile.Bordered = false;
			MarkDownFile.Bordered = false;
			XMLFile.Bordered = true;

			// Save selection
			DefaultLanguage = 3;
		}

		/// <summary>
		/// Creates a new document of the selected language type.
		/// </summary>
		/// <param name="sender">The object that started this action.</param>
		partial void ChooseDocument (Foundation.NSObject sender) {

			// Open new document window
			PerformSegue("OpenEditorSegue",this);

			// Close this window
			View.Window.PerformClose(this);
		}
		#endregion
	}
}
