// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CoreTextArcMonoMac {
	
	
	// Should subclass AppKit.NSView
	[Foundation.Register("CoreTextArcView")]
	public partial class CoreTextArcView {
	}
	
	// Should subclass Foundation.NSObject
	[Foundation.Register("FirstResponder")]
	public partial class FirstResponder {
		
		#pragma warning disable 0169
		[Foundation.Export("setDimsSubstitutedGlyphs:")]
		partial void setDimsSubstitutedGlyphs (AppKit.NSButton sender);

		[Foundation.Export("setShowsGlyphOutlines:")]
		partial void setShowsGlyphOutlines (AppKit.NSButton sender);

		[Foundation.Export("setShowsLineMetrics:")]
		partial void setShowsLineMetrics (AppKit.NSButton sender);

		[Foundation.Export("toggleBold:")]
		partial void toggleBold (AppKit.NSButton sender);

		[Foundation.Export("toggleItalic:")]
		partial void toggleItalic (AppKit.NSButton sender);
}
	
	// Should subclass AppKit.NSDocument
	[Foundation.Register("MyDocument")]
	public partial class MyDocument {
		
		private CoreTextArcView __mt_arcView;
		
		private global::AppKit.NSButton __mt_boldButton;
		
		private global::AppKit.NSButton __mt_italicButton;
		
		private global::AppKit.NSTextField __mt_txtField;
		
		#pragma warning disable 0169
		[Foundation.Connect("arcView")]
		private CoreTextArcView arcView {
			get {
				this.__mt_arcView = ((CoreTextArcView)(this.GetNativeField("arcView")));
				return this.__mt_arcView;
			}
			set {
				this.__mt_arcView = value;
				this.SetNativeField("arcView", value);
			}
		}
		
		[Foundation.Connect("boldButton")]
		private global::AppKit.NSButton boldButton {
			get {
				this.__mt_boldButton = ((global::AppKit.NSButton)(this.GetNativeField("boldButton")));
				return this.__mt_boldButton;
			}
			set {
				this.__mt_boldButton = value;
				this.SetNativeField("boldButton", value);
			}
		}
		
		[Foundation.Connect("italicButton")]
		private global::AppKit.NSButton italicButton {
			get {
				this.__mt_italicButton = ((global::AppKit.NSButton)(this.GetNativeField("italicButton")));
				return this.__mt_italicButton;
			}
			set {
				this.__mt_italicButton = value;
				this.SetNativeField("italicButton", value);
			}
		}
		
		[Foundation.Connect("txtField")]
		private global::AppKit.NSTextField txtField {
			get {
				this.__mt_txtField = ((global::AppKit.NSTextField)(this.GetNativeField("txtField")));
				return this.__mt_txtField;
			}
			set {
				this.__mt_txtField = value;
				this.SetNativeField("txtField", value);
			}
		}
	}
}
