// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DatePicker {
	
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("TestWindow")]
	public partial class TestWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("TestWindowController")]
	public partial class TestWindowController {
		
		private global::MonoMac.AppKit.NSColorWell __mt_backColorWell;
		
		private global::MonoMac.AppKit.NSButton __mt_bezeledCheck;
		
		private global::MonoMac.AppKit.NSButton __mt_borderedCheck;
		
		private global::MonoMac.AppKit.NSMatrix __mt_dateElementChecks;
		
		private global::MonoMac.AppKit.NSMatrix __mt_datePickerModeRadios;
		
		private global::MonoMac.AppKit.NSTextField __mt_dateResult1;
		
		private global::MonoMac.AppKit.NSTextField __mt_dateResult2;
		
		private global::MonoMac.AppKit.NSTextField __mt_dateResult3;
		
		private global::MonoMac.AppKit.NSTextField __mt_dateResult4;
		
		private global::MonoMac.AppKit.NSTextField __mt_dateResult5;
		
		private global::MonoMac.AppKit.NSButton __mt_drawsBackgroundCheck;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_fontSizePopup;
		
		private global::MonoMac.AppKit.NSDatePicker __mt_maxDatePicker;
		
		private global::MonoMac.AppKit.NSDatePicker __mt_minDatePicker;
		
		private global::MonoMac.AppKit.NSBox __mt_outerBox;
		
		private global::MonoMac.AppKit.NSDatePicker __mt_overrideDate;
		
		private global::MonoMac.AppKit.NSButton __mt_overrideDateCheck;
		
		private global::MonoMac.AppKit.NSPopUpButton __mt_pickerStylePopup;
		
		private global::MonoMac.AppKit.NSTextField __mt_secondsRangeEdit;
		
		private global::MonoMac.AppKit.NSTextField __mt_secondsRangeEditLabel;
		
		private global::MonoMac.AppKit.NSColorWell __mt_textColorWell;
		
		private global::MonoMac.AppKit.NSMatrix __mt_timeElementChecks;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("dateOverrideAction:")]
		partial void dateOverrideAction (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("dateOverrideChange:")]
		partial void dateOverrideChange (MonoMac.AppKit.NSDatePicker sender);

		[MonoMac.Foundation.Export("setBackgroundColor:")]
		partial void setBackgroundColor (MonoMac.AppKit.NSColorWell sender);

		[MonoMac.Foundation.Export("setBezeled:")]
		partial void setBezeled (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("setBordered:")]
		partial void setBordered (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("setDateElementFlags:")]
		partial void setDateElementFlags (MonoMac.AppKit.NSMatrix sender);

		[MonoMac.Foundation.Export("setDatePickerMode:")]
		partial void setDatePickerMode (MonoMac.AppKit.NSMatrix sender);

		[MonoMac.Foundation.Export("setDrawsBackground:")]
		partial void setDrawsBackground (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("setFontSize:")]
		partial void setFontSize (MonoMac.AppKit.NSPopUpButton sender);

		[MonoMac.Foundation.Export("setMaxDate:")]
		partial void setMaxDate (MonoMac.AppKit.NSDatePicker sender);

		[MonoMac.Foundation.Export("setMinDate:")]
		partial void setMinDate (MonoMac.AppKit.NSDatePicker sender);

		[MonoMac.Foundation.Export("setPickerStyle:")]
		partial void setPickerStyle (MonoMac.AppKit.NSPopUpButton sender);

		[MonoMac.Foundation.Export("setTextColor:")]
		partial void setTextColor (MonoMac.AppKit.NSColorWell sender);

		[MonoMac.Foundation.Export("setTimeElementFlags:")]
		partial void setTimeElementFlags (MonoMac.AppKit.NSMatrix sender);

		[MonoMac.Foundation.Export("setToToday:")]
		partial void setToToday (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("backColorWell")]
		private global::MonoMac.AppKit.NSColorWell backColorWell {
			get {
				this.__mt_backColorWell = ((global::MonoMac.AppKit.NSColorWell)(this.GetNativeField("backColorWell")));
				return this.__mt_backColorWell;
			}
			set {
				this.__mt_backColorWell = value;
				this.SetNativeField("backColorWell", value);
			}
		}
		
		[MonoMac.Foundation.Connect("bezeledCheck")]
		private global::MonoMac.AppKit.NSButton bezeledCheck {
			get {
				this.__mt_bezeledCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("bezeledCheck")));
				return this.__mt_bezeledCheck;
			}
			set {
				this.__mt_bezeledCheck = value;
				this.SetNativeField("bezeledCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("borderedCheck")]
		private global::MonoMac.AppKit.NSButton borderedCheck {
			get {
				this.__mt_borderedCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("borderedCheck")));
				return this.__mt_borderedCheck;
			}
			set {
				this.__mt_borderedCheck = value;
				this.SetNativeField("borderedCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateElementChecks")]
		private global::MonoMac.AppKit.NSMatrix dateElementChecks {
			get {
				this.__mt_dateElementChecks = ((global::MonoMac.AppKit.NSMatrix)(this.GetNativeField("dateElementChecks")));
				return this.__mt_dateElementChecks;
			}
			set {
				this.__mt_dateElementChecks = value;
				this.SetNativeField("dateElementChecks", value);
			}
		}
		
		[MonoMac.Foundation.Connect("datePickerModeRadios")]
		private global::MonoMac.AppKit.NSMatrix datePickerModeRadios {
			get {
				this.__mt_datePickerModeRadios = ((global::MonoMac.AppKit.NSMatrix)(this.GetNativeField("datePickerModeRadios")));
				return this.__mt_datePickerModeRadios;
			}
			set {
				this.__mt_datePickerModeRadios = value;
				this.SetNativeField("datePickerModeRadios", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateResult1")]
		private global::MonoMac.AppKit.NSTextField dateResult1 {
			get {
				this.__mt_dateResult1 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("dateResult1")));
				return this.__mt_dateResult1;
			}
			set {
				this.__mt_dateResult1 = value;
				this.SetNativeField("dateResult1", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateResult2")]
		private global::MonoMac.AppKit.NSTextField dateResult2 {
			get {
				this.__mt_dateResult2 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("dateResult2")));
				return this.__mt_dateResult2;
			}
			set {
				this.__mt_dateResult2 = value;
				this.SetNativeField("dateResult2", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateResult3")]
		private global::MonoMac.AppKit.NSTextField dateResult3 {
			get {
				this.__mt_dateResult3 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("dateResult3")));
				return this.__mt_dateResult3;
			}
			set {
				this.__mt_dateResult3 = value;
				this.SetNativeField("dateResult3", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateResult4")]
		private global::MonoMac.AppKit.NSTextField dateResult4 {
			get {
				this.__mt_dateResult4 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("dateResult4")));
				return this.__mt_dateResult4;
			}
			set {
				this.__mt_dateResult4 = value;
				this.SetNativeField("dateResult4", value);
			}
		}
		
		[MonoMac.Foundation.Connect("dateResult5")]
		private global::MonoMac.AppKit.NSTextField dateResult5 {
			get {
				this.__mt_dateResult5 = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("dateResult5")));
				return this.__mt_dateResult5;
			}
			set {
				this.__mt_dateResult5 = value;
				this.SetNativeField("dateResult5", value);
			}
		}
		
		[MonoMac.Foundation.Connect("drawsBackgroundCheck")]
		private global::MonoMac.AppKit.NSButton drawsBackgroundCheck {
			get {
				this.__mt_drawsBackgroundCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("drawsBackgroundCheck")));
				return this.__mt_drawsBackgroundCheck;
			}
			set {
				this.__mt_drawsBackgroundCheck = value;
				this.SetNativeField("drawsBackgroundCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("fontSizePopup")]
		private global::MonoMac.AppKit.NSPopUpButton fontSizePopup {
			get {
				this.__mt_fontSizePopup = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("fontSizePopup")));
				return this.__mt_fontSizePopup;
			}
			set {
				this.__mt_fontSizePopup = value;
				this.SetNativeField("fontSizePopup", value);
			}
		}
		
		[MonoMac.Foundation.Connect("maxDatePicker")]
		private global::MonoMac.AppKit.NSDatePicker maxDatePicker {
			get {
				this.__mt_maxDatePicker = ((global::MonoMac.AppKit.NSDatePicker)(this.GetNativeField("maxDatePicker")));
				return this.__mt_maxDatePicker;
			}
			set {
				this.__mt_maxDatePicker = value;
				this.SetNativeField("maxDatePicker", value);
			}
		}
		
		[MonoMac.Foundation.Connect("minDatePicker")]
		private global::MonoMac.AppKit.NSDatePicker minDatePicker {
			get {
				this.__mt_minDatePicker = ((global::MonoMac.AppKit.NSDatePicker)(this.GetNativeField("minDatePicker")));
				return this.__mt_minDatePicker;
			}
			set {
				this.__mt_minDatePicker = value;
				this.SetNativeField("minDatePicker", value);
			}
		}
		
		[MonoMac.Foundation.Connect("outerBox")]
		private global::MonoMac.AppKit.NSBox outerBox {
			get {
				this.__mt_outerBox = ((global::MonoMac.AppKit.NSBox)(this.GetNativeField("outerBox")));
				return this.__mt_outerBox;
			}
			set {
				this.__mt_outerBox = value;
				this.SetNativeField("outerBox", value);
			}
		}
		
		[MonoMac.Foundation.Connect("overrideDate")]
		private global::MonoMac.AppKit.NSDatePicker overrideDate {
			get {
				this.__mt_overrideDate = ((global::MonoMac.AppKit.NSDatePicker)(this.GetNativeField("overrideDate")));
				return this.__mt_overrideDate;
			}
			set {
				this.__mt_overrideDate = value;
				this.SetNativeField("overrideDate", value);
			}
		}
		
		[MonoMac.Foundation.Connect("overrideDateCheck")]
		private global::MonoMac.AppKit.NSButton overrideDateCheck {
			get {
				this.__mt_overrideDateCheck = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("overrideDateCheck")));
				return this.__mt_overrideDateCheck;
			}
			set {
				this.__mt_overrideDateCheck = value;
				this.SetNativeField("overrideDateCheck", value);
			}
		}
		
		[MonoMac.Foundation.Connect("pickerStylePopup")]
		private global::MonoMac.AppKit.NSPopUpButton pickerStylePopup {
			get {
				this.__mt_pickerStylePopup = ((global::MonoMac.AppKit.NSPopUpButton)(this.GetNativeField("pickerStylePopup")));
				return this.__mt_pickerStylePopup;
			}
			set {
				this.__mt_pickerStylePopup = value;
				this.SetNativeField("pickerStylePopup", value);
			}
		}
		
		[MonoMac.Foundation.Connect("secondsRangeEdit")]
		private global::MonoMac.AppKit.NSTextField secondsRangeEdit {
			get {
				this.__mt_secondsRangeEdit = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("secondsRangeEdit")));
				return this.__mt_secondsRangeEdit;
			}
			set {
				this.__mt_secondsRangeEdit = value;
				this.SetNativeField("secondsRangeEdit", value);
			}
		}
		
		[MonoMac.Foundation.Connect("secondsRangeEditLabel")]
		private global::MonoMac.AppKit.NSTextField secondsRangeEditLabel {
			get {
				this.__mt_secondsRangeEditLabel = ((global::MonoMac.AppKit.NSTextField)(this.GetNativeField("secondsRangeEditLabel")));
				return this.__mt_secondsRangeEditLabel;
			}
			set {
				this.__mt_secondsRangeEditLabel = value;
				this.SetNativeField("secondsRangeEditLabel", value);
			}
		}
		
		[MonoMac.Foundation.Connect("textColorWell")]
		private global::MonoMac.AppKit.NSColorWell textColorWell {
			get {
				this.__mt_textColorWell = ((global::MonoMac.AppKit.NSColorWell)(this.GetNativeField("textColorWell")));
				return this.__mt_textColorWell;
			}
			set {
				this.__mt_textColorWell = value;
				this.SetNativeField("textColorWell", value);
			}
		}
		
		[MonoMac.Foundation.Connect("timeElementChecks")]
		private global::MonoMac.AppKit.NSMatrix timeElementChecks {
			get {
				this.__mt_timeElementChecks = ((global::MonoMac.AppKit.NSMatrix)(this.GetNativeField("timeElementChecks")));
				return this.__mt_timeElementChecks;
			}
			set {
				this.__mt_timeElementChecks = value;
				this.SetNativeField("timeElementChecks", value);
			}
		}
	}
}
