// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NSTableViewBinding {
	
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("EditController")]
	public partial class EditController {
		
		private global::MonoMac.AppKit.NSForm __mt_editForm;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("cancel:")]
		partial void cancel (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("done:")]
		partial void done (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("editForm")]
		private global::MonoMac.AppKit.NSForm editForm {
			get {
				this.__mt_editForm = ((global::MonoMac.AppKit.NSForm)(this.GetNativeField("editForm")));
				return this.__mt_editForm;
			}
			set {
				this.__mt_editForm = value;
				this.SetNativeField("editForm", value);
			}
		}
	}
}
