// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NSTableViewBinding {
	
	
	// Should subclass MonoMac.AppKit.NSMatrix
	[Foundation.Register("NSForm")]
	public partial class NSForm {
	}
	
	// Should subclass MonoMac.AppKit.NSWindow
	[Foundation.Register("TestWindow")]
	public partial class TestWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[Foundation.Register("TestWindowController")]
	public partial class TestWindowController {
		
		private global::AppKit.NSButton __mt_addButton;
		
		private global::AppKit.NSArrayController __mt_myContentArray;
		
		private global::AppKit.NSForm __mt_myFormFields;
		
		private global::AppKit.NSTableView __mt_myTableView;
		
		private global::AppKit.NSButton __mt_removeButton;
		
		#pragma warning disable 0169
		[Foundation.Export("add:")]
		partial void add (AppKit.NSButton sender);

		[Foundation.Export("inspect:")]
		partial void inspect (Foundation.NSArray sender);

		[Foundation.Export("remove:")]
		partial void remove (AppKit.NSButton sender);

		[Foundation.Connect("addButton")]
		private global::AppKit.NSButton addButton {
			get {
				this.__mt_addButton = ((global::AppKit.NSButton)(this.GetNativeField("addButton")));
				return this.__mt_addButton;
			}
			set {
				this.__mt_addButton = value;
				this.SetNativeField("addButton", value);
			}
		}
		
		[Foundation.Connect("myContentArray")]
		private global::AppKit.NSArrayController myContentArray {
			get {
				this.__mt_myContentArray = ((global::AppKit.NSArrayController)(this.GetNativeField("myContentArray")));
				return this.__mt_myContentArray;
			}
			set {
				this.__mt_myContentArray = value;
				this.SetNativeField("myContentArray", value);
			}
		}
		
		[Foundation.Connect("myFormFields")]
		private global::AppKit.NSForm myFormFields {
			get {
				this.__mt_myFormFields = ((global::AppKit.NSForm)(this.GetNativeField("myFormFields")));
				return this.__mt_myFormFields;
			}
			set {
				this.__mt_myFormFields = value;
				this.SetNativeField("myFormFields", value);
			}
		}
		
		[Foundation.Connect("myTableView")]
		private global::AppKit.NSTableView myTableView {
			get {
				this.__mt_myTableView = ((global::AppKit.NSTableView)(this.GetNativeField("myTableView")));
				return this.__mt_myTableView;
			}
			set {
				this.__mt_myTableView = value;
				this.SetNativeField("myTableView", value);
			}
		}
		
		[Foundation.Connect("removeButton")]
		private global::AppKit.NSButton removeButton {
			get {
				this.__mt_removeButton = ((global::AppKit.NSButton)(this.GetNativeField("removeButton")));
				return this.__mt_removeButton;
			}
			set {
				this.__mt_removeButton = value;
				this.SetNativeField("removeButton", value);
			}
		}
	}
}
