// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NSTableViewBinding {
	
	
	// Should subclass MonoMac.AppKit.NSMatrix
	[MonoMac.Foundation.Register("NSForm")]
	public partial class NSForm {
	}
	
	// Should subclass MonoMac.AppKit.NSWindow
	[MonoMac.Foundation.Register("TestWindow")]
	public partial class TestWindow {
	}
	
	// Should subclass MonoMac.AppKit.NSWindowController
	[MonoMac.Foundation.Register("TestWindowController")]
	public partial class TestWindowController {
		
		private global::MonoMac.AppKit.NSButton __mt_addButton;
		
		private global::MonoMac.AppKit.NSArrayController __mt_myContentArray;
		
		private global::MonoMac.AppKit.NSForm __mt_myFormFields;
		
		private global::MonoMac.AppKit.NSTableView __mt_myTableView;
		
		private global::MonoMac.AppKit.NSButton __mt_removeButton;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("add:")]
		partial void add (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Export("inspect:")]
		partial void inspect (MonoMac.Foundation.NSArray sender);

		[MonoMac.Foundation.Export("remove:")]
		partial void remove (MonoMac.AppKit.NSButton sender);

		[MonoMac.Foundation.Connect("addButton")]
		private global::MonoMac.AppKit.NSButton addButton {
			get {
				this.__mt_addButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("addButton")));
				return this.__mt_addButton;
			}
			set {
				this.__mt_addButton = value;
				this.SetNativeField("addButton", value);
			}
		}
		
		[MonoMac.Foundation.Connect("myContentArray")]
		private global::MonoMac.AppKit.NSArrayController myContentArray {
			get {
				this.__mt_myContentArray = ((global::MonoMac.AppKit.NSArrayController)(this.GetNativeField("myContentArray")));
				return this.__mt_myContentArray;
			}
			set {
				this.__mt_myContentArray = value;
				this.SetNativeField("myContentArray", value);
			}
		}
		
		[MonoMac.Foundation.Connect("myFormFields")]
		private global::MonoMac.AppKit.NSForm myFormFields {
			get {
				this.__mt_myFormFields = ((global::MonoMac.AppKit.NSForm)(this.GetNativeField("myFormFields")));
				return this.__mt_myFormFields;
			}
			set {
				this.__mt_myFormFields = value;
				this.SetNativeField("myFormFields", value);
			}
		}
		
		[MonoMac.Foundation.Connect("myTableView")]
		private global::MonoMac.AppKit.NSTableView myTableView {
			get {
				this.__mt_myTableView = ((global::MonoMac.AppKit.NSTableView)(this.GetNativeField("myTableView")));
				return this.__mt_myTableView;
			}
			set {
				this.__mt_myTableView = value;
				this.SetNativeField("myTableView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("removeButton")]
		private global::MonoMac.AppKit.NSButton removeButton {
			get {
				this.__mt_removeButton = ((global::MonoMac.AppKit.NSButton)(this.GetNativeField("removeButton")));
				return this.__mt_removeButton;
			}
			set {
				this.__mt_removeButton = value;
				this.SetNativeField("removeButton", value);
			}
		}
	}
}
