// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace StillMotion {
	
	
	// Should subclass MonoMac.AppKit.NSDocument
	[MonoMac.Foundation.Register("StillMotionDocument")]
	public partial class StillMotionDocument {
		
		private global::MonoMac.QTKit.QTCaptureView __mt_captureView;
		
		private global::MonoMac.QTKit.QTMovieView __mt_movieView;
		
		#pragma warning disable 0169
		[MonoMac.Foundation.Export("addFrame:")]
		partial void addFrame (MonoMac.Foundation.NSObject sender);

		[MonoMac.Foundation.Connect("captureView")]
		private global::MonoMac.QTKit.QTCaptureView captureView {
			get {
				this.__mt_captureView = ((global::MonoMac.QTKit.QTCaptureView)(this.GetNativeField("captureView")));
				return this.__mt_captureView;
			}
			set {
				this.__mt_captureView = value;
				this.SetNativeField("captureView", value);
			}
		}
		
		[MonoMac.Foundation.Connect("movieView")]
		private global::MonoMac.QTKit.QTMovieView movieView {
			get {
				this.__mt_movieView = ((global::MonoMac.QTKit.QTMovieView)(this.GetNativeField("movieView")));
				return this.__mt_movieView;
			}
			set {
				this.__mt_movieView = value;
				this.SetNativeField("movieView", value);
			}
		}
	}
}
